### PR TITLE
added daemon mode

### PR DESCRIPTION
**Pull request by bosky101**
Hi, I added a daemon mode ( for fun and profit! ) 

I put a wrapper around the logging so that it can write to syslog when in daemon mode.

```
   ./lib-face -h
   ...
   -d, --daemon  Whether to run as daemon & write to syslog (default: not daemon)

   ./lib-face -d
```

I've split the contribution as 3 small commits for clarity. Couldn't commit to the wiki though.

Regards,
~Bosky

### CODE REVIEW

**Comment by dhruvbird** [comment]
Hi! Thanks for the patch. I'll be more than happy to merge it! However, is it possible for you to add options to allow compilation on systems that don't have syslog.h? Probably the Makefile can check if syslog.h exists and set a compilation flag, or maybe use configure (the latter seems a bit heavy though).

**Comment by dhruvbird** [comment]
Oops, I also forgot to mention - please could you also provide an update for the QuickStartGuide wiki page with the appropriate options & their arguments mentioned so that others can use it. Thanks!

**Comment by bosky101** [comment]
thanks for reverting, you're right.

i didnt find the wiki in the repo, guess i'll have to pull it seperately.

will do it over the weekend, and push again. you can close this pull request.

~B

**Comment by dhruvbird** [comment]
@bosky101 Thanks!
fyi, here is the wiki git url: git@github.com:duckduckgo/cpp-libface.wiki.git

I've already cherry picked this commit though since it was small enough and independent of the rest: https://github.com/bosky101/cpp-libface/commit/902e3341f4c358f757f0f6b74784a9dd1cb184fb

**Comment by dhruvbird** [comment]
@bosky101 Let me know if you are unable to send a pull request on the wiki git repo. I'll add your remote and cherry-pick or merge branches as appropriate.

**Comment by bosky101** [comment]
actually https://github.com/bosky101/cpp-libface/commit/0712a29eb831b2e29bddee38ee570968fcd5d748 is also independent of syslog

only https://github.com/bosky101/cpp-libface/commit/04db12e0e81817671b9c6bc443ed5ebec8309f3d added syslog

**Comment by dhruvbird** [comment]
@bosky101 Additionally, there is code that uses relative paths (such as import & export), which will fail in daemon mode unless absolute paths are specified. This should also be fixed in daemon mode.

**Comment by dhruvbird** [comment]
Or maybe save the $PWD in a local variable and check if the import path is absolute/relative and either use it or append it to the previous $PWD before import/export-ing.

**Pull request closed without merging**
